# If you have OpenSSL installed, we recommend updating the following line to
# use "https".
source 'http://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
gem 'middleman', '~> 4.0.0'
gem 'middleman-blog', '~> 4.0.0'
gem 'middleman-livereload', '~> 3.4.5'
gem 'middleman-sprockets', '~> 4.0.0.rc'

# For feed.xml.builder
gem 'builder', '~> 3.2.2'

# Code syntax highlighting
gem 'middleman-syntax', '~> 2.1.0'
gem 'redcarpet', '~> 3.3.4'

# For "summary"-Helper
gem 'nokogiri', '~> 1.6.7.1'
