# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.1', platforms: [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
gem 'middleman', '>= 4.0.0'
gem 'middleman-blog', '>= 4.0.0'
gem 'middleman-sprockets', '>= 4.0.0.rc.2'

# For feed.xml.builder
gem 'builder', '~> 3.2.2'

# Code syntax highlighting
gem 'middleman-syntax', '~> 2.1.0'
gem 'redcarpet', '~> 3.3.4'

# For "summary"-Helper
gem 'nokogiri', '~> 1.6.7.2'
